In [2]:
import numpy as np

### The Basics of Numpy

In [3]:
a = np.array([1,2,3],dtype = 'int8')
print(a)

[1 2 3]


In [4]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [5]:
a.ndim

1

In [6]:
b.ndim

2

In [7]:
a.shape

(3,)

In [8]:
b.shape

(2, 3)

In [9]:
a.itemsize

1

In [10]:
a.dtype

dtype('int8')

In [11]:
a.nbytes

3

In [12]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print (a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [13]:
a[1,4]

12

In [14]:
a[0,3:6]

array([4, 5, 6])

In [15]:
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [16]:
a[:,2]

array([ 3, 10])

In [17]:
a[0,1:-1:2]

array([2, 4, 6])

In [18]:
a[0,:-1]

array([1, 2, 3, 4, 5, 6])

In [19]:
a[0,5:-1]

array([6])

In [20]:
a[0,-3:-1]

array([5, 6])

In [21]:
a[0,3]=3
a

array([[ 1,  2,  3,  3,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [22]:
a[:,2]=17
a

array([[ 1,  2, 17,  3,  5,  6,  7],
       [ 8,  9, 17, 11, 12, 13, 14]])

In [24]:
a[:,1]=3
a

array([[ 1,  3, 17,  3,  5,  6,  7],
       [ 8,  3, 17, 11, 12, 13, 14]])

In [27]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [31]:
C=np.ones((4,2,2), dtype='int16')
print(C)

[[[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]]


In [33]:
np.full((2,2),9)

array([[9, 9],
       [9, 9]])

In [34]:
np.full_like(a,2)

array([[2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2]])

In [38]:
np.random.rand(4,2)

array([[0.90376942, 0.27851791],
       [0.11083696, 0.11391591],
       [0.94947672, 0.61392833],
       [0.04828799, 0.83756512]])

In [40]:
np.random.randint(-6,10,size=(3,3))

array([[ 9,  2, -4],
       [ 9,  3,  3],
       [-4,  7, -2]])

In [44]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [51]:
arr=np.array([[1,2,3]])
re=np.repeat(arr,3,axis=0)
re

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [56]:
output = np.ones((5,5))
output

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [59]:
z=np.zeros((3,3))
z[1,1]=9
z

array([[0., 0., 0.],
       [0., 9., 0.],
       [0., 0., 0.]])

In [60]:
output[1:-1,1:-1]

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [81]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [67]:
b=a.copy()
b

array([1, 2, 3])

In [76]:
a+2

array([3, 4, 5])

In [78]:
a*=2
a

array([2, 4, 6])

In [80]:
a//2

array([1, 2, 3])

In [83]:
a*=3
b*=4

In [86]:
a+b

array([25, 50, 75])

In [87]:
a*b

array([ 144,  576, 1296])

In [89]:
np.cos(a)

array([-0.91113026,  0.66031671, -0.29213881])

In [90]:
np.sin(b)

array([-0.28790332,  0.55142668, -0.76825466])

In [99]:
np.tan(a)

array([[1.55740772, 1.55740772, 1.55740772],
       [1.55740772, 1.55740772, 1.55740772]])

In [97]:
a=np.ones((2,3))
b=np.full((3,2),2)
print(a)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [103]:
c=np.matmul(a,b)
c

array([[6., 6.],
       [6., 6.]])

In [108]:

c[1,0]=3
np.linalg.det(c)

17.999999999999996