In [ ]:
import numpy as np

### The Basics of Numpy

In [ ]:
a = np.array([1,2,3],dtype = 'int8')
print(a)

[1 2 3]


In [ ]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [ ]:
a.ndim

1

In [ ]:
b.ndim

2

In [ ]:
a.shape

(3,)

In [ ]:
b.shape

(2, 3)

In [ ]:
a.itemsize

4

In [ ]:
a.dtype

dtype('int32')

In [ ]:
a.nbytes

3

In [29]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print (a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [32]:
a[1,4]

12

In [34]:
a[0,3:6]

array([4, 5, 6])