In [2]:
import numpy as np

### The Basics of Numpy

In [3]:
a = np.array([1,2,3],dtype = 'int8')
print(a)

[1 2 3]


In [4]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [5]:
a.ndim

1

In [6]:
b.ndim

2

In [7]:
a.shape

(3,)

In [8]:
b.shape

(2, 3)

In [9]:
a.itemsize

1

In [10]:
a.dtype

dtype('int8')

In [11]:
a.nbytes

3

In [12]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print (a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [13]:
a[1,4]

12

In [14]:
a[0,3:6]

array([4, 5, 6])

In [15]:
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [16]:
a[:,2]

array([ 3, 10])

In [17]:
a[0,1:-1:2]

array([2, 4, 6])

In [18]:
a[0,:-1]

array([1, 2, 3, 4, 5, 6])

In [19]:
a[0,5:-1]

array([6])

In [20]:
a[0,-3:-1]

array([5, 6])

In [21]:
a[0,3]=3
a

array([[ 1,  2,  3,  3,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [22]:
a[:,2]=17
a

array([[ 1,  2, 17,  3,  5,  6,  7],
       [ 8,  9, 17, 11, 12, 13, 14]])

In [24]:
a[:,1]=3
a

array([[ 1,  3, 17,  3,  5,  6,  7],
       [ 8,  3, 17, 11, 12, 13, 14]])

In [27]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [31]:
C=np.ones((4,2,2), dtype='int16')
print(C)

[[[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]]


In [32]:
np.full((2,2),9)

array([[9, 9],
       [9, 9]])