In [1]:
import numpy as np

### The Basics of Numpy

In [2]:
a = np.array([1,2,3],dtype = 'int8')
print(a)

[1 2 3]


In [3]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [4]:
a.ndim

1

In [5]:
b.ndim

2

In [6]:
a.shape

(3,)

In [7]:
b.shape

(2, 3)

In [8]:
a.itemsize

1

In [9]:
a.dtype

dtype('int8')

In [10]:
a.nbytes

3

In [11]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print (a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [12]:
a[1,4]

12

In [13]:
a[0,3:6]

array([4, 5, 6])

In [14]:
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [15]:
a[:,2]

array([ 3, 10])

In [16]:
a[0,1:-1:2]

array([2, 4, 6])

In [17]:
a[0,:-1]

array([1, 2, 3, 4, 5, 6])

In [18]:
a[0,5:-1]

array([6])

In [19]:
a[0,-3:-1]

array([5, 6])

In [20]:
a[0,3]=3
a

array([[ 1,  2,  3,  3,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [21]:
a[:,2]=17
a

array([[ 1,  2, 17,  3,  5,  6,  7],
       [ 8,  9, 17, 11, 12, 13, 14]])

In [22]:
a[:,1]=3
a

array([[ 1,  3, 17,  3,  5,  6,  7],
       [ 8,  3, 17, 11, 12, 13, 14]])

In [23]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [24]:
C=np.ones((4,2,2), dtype='int16')
print(C)

[[[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]]


In [25]:
np.full((2,2),9)

array([[9, 9],
       [9, 9]])

In [26]:
np.full_like(a,2)

array([[2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2]])

In [27]:
np.random.rand(4,2)

array([[0.25867078, 0.06594017],
       [0.03921689, 0.18922946],
       [0.55960252, 0.92064384],
       [0.47857359, 0.83134248]])

In [28]:
np.random.randint(-6,10,size=(3,3))

array([[-6,  2,  5],
       [ 8,  0,  3],
       [ 2, -5, -1]])

In [29]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
arr=np.array([[1,2,3]])
re=np.repeat(arr,3,axis=0)
re

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [31]:
output = np.ones((5,5))
output

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [32]:
z=np.zeros((3,3))
z[1,1]=9
z

array([[0., 0., 0.],
       [0., 9., 0.],
       [0., 0., 0.]])

In [33]:
output[1:-1,1:-1]

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [34]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [35]:
b=a.copy()
b

array([1, 2, 3])

In [36]:
a+2

array([3, 4, 5])

In [37]:
a*=2
a

array([2, 4, 6])

In [38]:
a//2

array([1, 2, 3], dtype=int32)

In [39]:
a*=3
b*=4

In [40]:
a+b

array([10, 20, 30])

In [41]:
a*b

array([ 24,  96, 216])

In [42]:
np.cos(a)

array([0.96017029, 0.84385396, 0.66031671])

In [43]:
np.sin(b)

array([-0.7568025 ,  0.98935825, -0.53657292])

In [44]:
np.tan(a)

array([-0.29100619, -0.63585993, -1.13731371])

In [45]:
a=np.ones((2,3))
b=np.full((3,2),2)
print(a)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [46]:
c=np.matmul(a,b)
c

array([[6., 6.],
       [6., 6.]])

In [47]:

c[1,0]=4
print(c)
np.linalg.det(c)

[[6. 6.]
 [4. 6.]]


12.0

In [48]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [49]:
np.min(stats)

1

In [50]:
np.max(stats)

6

In [51]:
np.max(stats,axis=0)

array([4, 5, 6])

In [52]:
np.sum(stats,axis=1)

array([ 6, 15])

In [53]:
stats.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [54]:
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])
np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [55]:
np.hstack([v1,v2])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [59]:
datas = np.genfromtxt('data.txt',delimiter=',')
datas = datas.astype('int32')
print(datas)

[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5
   3  42   1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1
  76  88  12  33 761  75 441  55   6   4   3   4   5   6   7   0  11   1
 232 331 121  19 121 233  12 718  20 331 662 932  28 127 512 376 288 441
  55   6   4   3   4   5   6   7   0 112  76  88  12  33 761  75 441  55
   6   4   3   4   5   6   7   0  11   1  22  33  11 999  11   2   1  78
   0   1   2   9   8   7   1  76  88]


In [61]:
(~((datas > 50) & (datas < 100)))

array([ True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
       False, False,  True,  True,  True, False,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False, False,  True,  True,  True, False,  True, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True,  True,  True, False, False])